version: '3.3'
services:
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-odoo}
      POSTGRES_USER: ${DB_USER:-odoo}
      POSTGRES_DB: ${DB_NAME:-postgres}
    restart: always

  odoo:
    image: mkubit/odoo
    build:
      context: odoo
    depends_on:
      - db
    ports:
      - "8071:8069"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - odoo_data:/var/lib/odoo
    restart: always

volumes:
  odoo_data:
